#!/bin/sh /etc/rc.common

USE_PROCD=1
START=96
STOP=4

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/sd-wrt-policy
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    local pid
    pid=$(pgrep -f sd-wrt-policy | head -1)
    [ -n "$pid" ] && kill -HUP "$pid"
}
